<template>
    <el-menu
        :collapse="getNavMenuCollapse"
        mode="vertical"
        :collapse-transition="false"
        :default-active="currentUrl"
        class="scroll layout-menu-content"
        :unique-opened="true"
    >
        <nav-menu-sub-menu v-for="menu in menuDatas" :key="menu.id"
            :sub-menu-items="menu"
        />
    </el-menu>
</template>
<script>
import {mapGetters} from 'vuex'
export default {
    name: 'NavMenu',
    components: {
        NavMenuSubMenu: () => import('./nav-menu-sub-menu.vue')
    },
    data() {
        return {
            url: ''
        }
    },
    computed: {
        ...mapGetters(['menuDatas', 'getNavMenuCollapse']),
        currentUrl() {
            return this.$route.path
        },
        menuDatas() {
            let menuData = [{
                "allCaption":"管理后台-个人中心",
                "appName":"政务监督",
                "caption":"窗口服务人员录入",
                "description":"",
                "enable":true,
                "id":10001,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":1,
                "subFuncItems":[],
                "subMenuItems":[],
                "url":"/home"
            },{
                "allCaption":"管理后台-系统管理-角色管理",
                "appName":"政务监督",
                "caption":"考勤情况录入",
                "description":"",
                "enable":true,
                "id":10024,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":2,
                "subFuncItems":[],
                "subMenuItems":[],
                "url":"/attendance/index"
            },{
                "allCaption":"管理后台-项目资料管理",
                "appName":"政务监督",
                "caption":"★月度服务之星录入",
                "description":"",
                "enable":true,
                "id":10003,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":3,
                "subFuncItems":[],
                "subMenuItems":[],
                "url":"/star/index"
            },{
                "allCaption":"管理后台-诉求管理",
                "appName":"政务监督",
                "caption":"政务服务质量录入",
                "description":"",
                "enable":true,
                "id":10004,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":4,
                "subFuncItems":[],
                "subMenuItems":[],
                "url":"/rate"
            },{
                "allCaption":"管理后台-系统管理",
                "appName":"政务监督",
                "caption":"大厅设施情况录入",
                "description":"",
                "enable":true,
                "id":10006,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":5,
                "subFuncItems":[],
                "subMenuItems":[],
                "url":"/hallDevice"
            },{
                "allCaption":"管理后台-系统管理-角色管理",
                "appName":"政务监督",
                "caption":"政务服务事项录入",
                "description":"",
                "enable":true,
                "id":10025,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":6,
                "subFuncItems":[],
                "subMenuItems":[],
                "url":"/governmentEntry"
            },{
                "allCaption":"政策兑现整体情况录入",
                "appName":"政务监督",
                "caption":"政策兑现整体情况录入",
                "description":"",
                "enable":true,
                "id":10109,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":7,
                "subFuncItems":[],
                "subMenuItems":[
                    {
                        "allCaption":"政策兑现受理量录入",
                        "appName":"政务监督",
                        "caption":"政策兑现受理量统计录入",
                        "description":"",
                        "enable":true,
                        "id":10110,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10109,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":7,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/policyEnter/policyCashAcceptAmount"
                    },
                    {
                        "allCaption":"政策兑现受理量录入",
                        "appName":"政务监督",
                        "caption":"政策兑现预审量统计录入",
                        "description":"",
                        "enable":true,
                        "id":10111,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10109,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":7,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/policyEnter/policyCashPretrialAmount"
                    },
                    {
                        "allCaption":"政策兑现受理量录入",
                        "appName":"政务监督",
                        "caption":"政策受理量Top6统计录入",
                        "description":"",
                        "enable":true,
                        "id":10112,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10109,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":7,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/policyEnter/policyAcceptAmount"
                    },
                    {
                        "allCaption":"政策兑现受理量录入",
                        "appName":"政务监督",
                        "caption":"已发布政策事项录入",
                        "description":"",
                        "enable":true,
                        "id":10113,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10109,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":7,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/policyEnter/publishPolicy"
                    },
                    {
                        "allCaption":"政策兑现受理量录入",
                        "appName":"政务监督",
                        "caption":"政策兑现流程统计录入",
                        "description":"",
                        "enable":true,
                        "id":10114,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10109,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":7,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/policyEnter/policyCashWork"
                    }
                ],
                "url":"/policyEnter"
            },{
                "allCaption":"企业政策兑现情况录入",
                "appName":"政务监督",
                "caption":"企业政策兑现情况录入",
                "description":"",
                "enable":true,
                "id":10101,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":8,
                "subFuncItems":[],
                "subMenuItems":[
                    {
                        "allCaption":"企业政策兑现情况录入",
                        "appName":"政务监督",
                        "caption":"镇街企业数录入",
                        "description":"",
                        "enable":true,
                        "id":10102,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10101,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":8,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/firmPolicyEnter/townFirmCount"
                    },
                    {
                        "allCaption":"企业政策兑现情况录入",
                        "appName":"政务监督",
                        "caption":"企业所属行业统计录入",
                        "description":"",
                        "enable":true,
                        "id":10103,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10101,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":8,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/firmPolicyEnter/firmTheirTmt"
                    },
                    {
                        "allCaption":"企业政策兑现情况录入",
                        "appName":"政务监督",
                        "caption":"企业类型统计录入",
                        "description":"",
                        "enable":true,
                        "id":10104,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10101,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":8,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/firmPolicyEnter/firmType"
                    },
                    {
                        "allCaption":"企业政策兑现情况录入",
                        "appName":"政务监督",
                        "caption":"申请奖励类别统计录入",
                        "description":"",
                        "enable":true,
                        "id":10105,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10101,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":8,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/firmPolicyEnter/applyReward"
                    },
                    {
                        "allCaption":"企业政策兑现情况录入",
                        "appName":"政务监督",
                        "caption":"产业政策类累计浏览量录入",
                        "description":"",
                        "enable":true,
                        "id":10106,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10101,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":8,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/firmPolicyEnter/industryPolicyBrowseAmount"
                    },
                    {
                        "allCaption":"企业政策兑现情况录入",
                        "appName":"政务监督",
                        "caption":"热门产业政策事项累计浏览量录入",
                        "description":"",
                        "enable":true,
                        "id":10107,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10101,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":8,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/firmPolicyEnter/hotIndustryPolicyBrowseAmount"
                    },
                    {
                        "allCaption":"企业政策兑现情况录入",
                        "appName":"政务监督",
                        "caption":"近30天热门企业事项浏览量录入",
                        "description":"",
                        "enable":true,
                        "id":10108,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10101,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":8,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/firmPolicyEnter/hotFirmBrowerAmount"
                    }
                ],
                "url":"/firmPolicyEnter"
            },{
                "allCaption":"人才政策兑现情况录入",
                "appName":"政务监督",
                "caption":"人才政策兑现情况录入",
                "description":"",
                "enable":true,
                "id":10115,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":9,
                "subFuncItems":[],
                "subMenuItems":[
                    {
                        "allCaption":"人才所在行业录入",
                        "appName":"政务监督",
                        "caption":"人才所在行业分布统计录入",
                        "description":"",
                        "enable":true,
                        "id":10116,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10115,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":9,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/talentsPolicyEnter/talentTheirTmt"
                    },
                    {
                        "allCaption":"人才国籍分布录入",
                        "appName":"政务监督",
                        "caption":"人才国籍分布录入",
                        "description":"",
                        "enable":true,
                        "id":10117,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10115,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":9,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/talentsPolicyEnter/talentNataionalityDistribu"
                    },
                    {
                        "allCaption":"人才学历录入",
                        "appName":"政务监督",
                        "caption":"人才学历统计录入",
                        "description":"",
                        "enable":true,
                        "id":10118,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10115,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":9,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/talentsPolicyEnter/talentEducation"
                    },
                    {
                        "allCaption":"人才年龄分布",
                        "appName":"政务监督",
                        "caption":"人才年龄分布",
                        "description":"",
                        "enable":true,
                        "id":10119,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10115,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":9,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/talentsPolicyEnter/talentAgeDistribu"
                    },
                    {
                        "allCaption":"人才持卡数",
                        "appName":"政务监督",
                        "caption":"人才持卡数统计录入",
                        "description":"",
                        "enable":true,
                        "id":10120,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10115,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":9,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/talentsPolicyEnter/talentCardAmount"
                    },
                    {
                        "allCaption":"热门人才事项浏览量录入",
                        "appName":"政务监督",
                        "caption":"热门人才事项累计浏览量",
                        "description":"",
                        "enable":true,
                        "id":10121,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10115,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":9,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/talentsPolicyEnter/hotTalentBrowerAmount"
                    },
                    {
                        "allCaption":"人才版块总览数录入",
                        "appName":"政务监督",
                        "caption":"人才版块总览数录入",
                        "description":"",
                        "enable":true,
                        "id":10122,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10115,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":9,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/talentsPolicyEnter/talentSectionTotal"
                    },
                    {
                        "allCaption":"镇街人才分布录入",
                        "appName":"政务监督",
                        "caption":"镇街人才分布录入",
                        "description":"",
                        "enable":true,
                        "id":10126,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10115,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":9,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/talentsPolicyEnter/townStreetTalentDistributionEntry"
                    }
                ],
                "url":"/talentsPolicyEnter"
            },{
                "allCaption":"可视化图表配置",
                "appName":"政务监督",
                "caption":"可视化图表配置",
                "description":"",
                "enable":true,
                "id":10141,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":10,
                "subFuncItems":[],
                "subMenuItems":[
                    {
                        "allCaption":"可视化图表配置",
                        "appName":"政务监督",
                        "caption":"政策兑现专题",
                        "description":"",
                        "enable":true,
                        "id":10138,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10141,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":1,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/largeScreenChartConfiguration/policyImplementation"
                    },
                    {
                        "allCaption":"可视化图表配置",
                        "appName":"政务监督",
                        "caption":"企业政策兑现专题",
                        "description":"",
                        "enable":true,
                        "id":10139,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10141,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":2,
                        "subFuncItems":[],
                        "subMenuItems":[{
                            "allCaption":"可视化图表配置",
                            "appName":"政务监督",
                            "caption":"企业政策兑现专题2",
                            "description":"",
                            "enable":true,
                            "id":10139,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":{
                                "allCaption":"",
                                "appName":"",
                                "caption":"",
                                "description":"",
                                "enable":false,
                                "id":1014222,
                                "imgCss":"",
                                "openType":"",
                                "parentMenuItemDTO":null,
                                "position":null,
                                "subFuncItems":[],
                                "subMenuItems":[],
                                "url":""
                            },
                            "position":2,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":"/largeScreenChartConfiguration/enterprisePolicyImplementation/aaaaaaaaaa"
                        }],
                        "url":"/largeScreenChartConfiguration/enterprisePolicyImplementation"
                    },
                    {
                        "allCaption":"可视化图表配置",
                        "appName":"政务监督",
                        "caption":"人才政策兑现专题",
                        "description":"",
                        "enable":true,
                        "id":10140,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10141,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":3,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/largeScreenChartConfiguration/talentPolicyImplementation"
                    }
                ],
                "url":"/largeScreenChartConfiguration"
            },{
                "allCaption":"管理后台-个人中心消息列表",
                "appName":"政务监督",
                "caption":"数据报送录入",
                "description":"",
                "enable":true,
                "id":10009,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":11,
                "subFuncItems":[
                    {
                        "allCaption":"",
                        "caption":"全部",
                        "code":"8",
                        "description":"",
                        "enable":true,
                        "id":8,
                        "menu":null,
                        "method":"",
                        "position":4,
                        "url":" "
                    },
                    {
                        "allCaption":"",
                        "caption":"我发起的",
                        "code":"9",
                        "description":"",
                        "enable":true,
                        "id":9,
                        "menu":null,
                        "method":"",
                        "position":5,
                        "url":" "
                    },
                    {
                        "allCaption":"",
                        "caption":"待办",
                        "code":"10",
                        "description":"",
                        "enable":true,
                        "id":10,
                        "menu":null,
                        "method":"",
                        "position":6,
                        "url":" "
                    },
                    {
                        "allCaption":"",
                        "caption":"已办",
                        "code":"12",
                        "description":"",
                        "enable":true,
                        "id":12,
                        "menu":null,
                        "method":"",
                        "position":7,
                        "url":" "
                    },
                    {
                        "allCaption":"",
                        "caption":"待阅",
                        "code":"11",
                        "description":"",
                        "enable":true,
                        "id":11,
                        "menu":null,
                        "method":"",
                        "position":8,
                        "url":" "
                    },
                    {
                        "allCaption":"",
                        "caption":"已阅",
                        "code":"13",
                        "description":"",
                        "enable":true,
                        "id":13,
                        "menu":null,
                        "method":"",
                        "position":9,
                        "url":" "
                    }
                ],
                "subMenuItems":[],
                "url":"/dataEnter"
            },{
                "allCaption":"政策兑现办理统计",
                "appName":"政务监督",
                "caption":"政策兑现办理统计",
                "description":"",
                "enable":true,
                "id":10123,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":12,
                "subFuncItems":[],
                "subMenuItems":[
                    {
                        "allCaption":"办理超期统计",
                        "appName":"政务监督",
                        "caption":"办理超期统计",
                        "description":"",
                        "enable":true,
                        "id":10124,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10123,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":12,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/policyFulfillmentProcessingStatistics/handlingOverdueStatistics"
                    },
                    {
                        "allCaption":"政策兑现详情统计",
                        "appName":"政务监督",
                        "caption":"政策兑现详情统计",
                        "description":"",
                        "enable":true,
                        "id":10125,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10123,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":12,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/policyFulfillmentProcessingStatistics/policyFulfillmentDetailsStatistics"
                    }
                ],
                "url":"/policyFulfillmentProcessingStatistics"
            },{
                "allCaption":"小程序",
                "appName":"政务监督",
                "caption":"表单设计",
                "description":"",
                "enable":true,
                "id":10010,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":13,
                "subFuncItems":[],
                "subMenuItems":[],
                "url":"/vform-zwjd/form/list"
            },{
                "allCaption":"管理后台-政策通知公告-政策公告",
                "appName":"政务监督",
                "caption":"积木报表",
                "description":"",
                "enable":true,
                "id":10014,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":14,
                "subFuncItems":[],
                "subMenuItems":[],
                "url":"/vform-zwjd/buildReport"
            },{
                "allCaption":"管理后台-政策通知公告-通知公告",
                "appName":"政务监督",
                "caption":"特定对象管理",
                "description":"",
                "enable":true,
                "id":10015,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":15,
                "subFuncItems":[],
                "subMenuItems":[],
                "url":"/vform-zwjd/crowd/list"
            },{
                "allCaption":"管理后台-政策通知公告-通知公告",
                "appName":"政务监督",
                "caption":"统计数据",
                "description":"",
                "enable":true,
                "id":10026,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":16,
                "subFuncItems":[],
                "subMenuItems":[],
                "url":"/vform-zwjd/statics/index"
            },{
                "allCaption":"管理后台-系统管理-角色管理",
                "appName":"政务监督",
                "caption":"系统管理",
                "description":"",
                "enable":true,
                "id":10017,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":17,
                "subFuncItems":[],
                "subMenuItems":[
                    {
                        "allCaption":"管理后台-系统管理-部门管理",
                        "appName":"政务监督",
                        "caption":"部门管理",
                        "description":"",
                        "enable":true,
                        "id":10018,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10017,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":17,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/admin/organization"
                    },
                    {
                        "allCaption":"管理后台-系统管理-角色管理",
                        "appName":"政务监督",
                        "caption":"角色管理",
                        "description":"",
                        "enable":true,
                        "id":10022,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10017,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":17,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/admin/roles"
                    },
                    {
                        "allCaption":"管理后台-系统管理-角色管理",
                        "appName":"政务监督",
                        "caption":"用户管理",
                        "description":"",
                        "enable":true,
                        "id":10023,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10017,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":17,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/admin/users"
                    },
                    {
                        "allCaption":"管理后台-系统管理-角色管理",
                        "appName":"政务监督",
                        "caption":"日志管理",
                        "description":"",
                        "enable":true,
                        "id":10137,
                        "imgCss":"",
                        "openType":"",
                        "parentMenuItemDTO":{
                            "allCaption":"",
                            "appName":"",
                            "caption":"",
                            "description":"",
                            "enable":false,
                            "id":10017,
                            "imgCss":"",
                            "openType":"",
                            "parentMenuItemDTO":null,
                            "position":null,
                            "subFuncItems":[],
                            "subMenuItems":[],
                            "url":""
                        },
                        "position":17,
                        "subFuncItems":[],
                        "subMenuItems":[],
                        "url":"/admin/logManagement"
                    }
                ],
                "url":"/admin"
            },{
                "allCaption":"报送小组配置",
                "appName":"政务监督",
                "caption":"报送小组配置",
                "description":"",
                "enable":true,
                "id":10127,
                "imgCss":"",
                "openType":"",
                "parentMenuItemDTO":null,
                "position":18,
                "subFuncItems":[
                    {
                        "allCaption":"",
                        "caption":"政策兑现组",
                        "code":"1",
                        "description":"",
                        "enable":true,
                        "id":1,
                        "menu":null,
                        "method":"GET",
                        "position":1,
                        "url":"953359308076060672"
                    },
                    {
                        "allCaption":"",
                        "caption":"企业帮办组",
                        "code":"2",
                        "description":"",
                        "enable":true,
                        "id":2,
                        "menu":null,
                        "method":"GET",
                        "position":2,
                        "url":"954014512755187712"
                    },
                    {
                        "allCaption":"",
                        "caption":"创新组",
                        "code":"3",
                        "description":"",
                        "enable":true,
                        "id":3,
                        "menu":null,
                        "method":"GET",
                        "position":3,
                        "url":"954324390858604544"
                    },
                    {
                        "allCaption":"",
                        "caption":"重点企业服务组",
                        "code":"4",
                        "description":"",
                        "enable":true,
                        "id":4,
                        "menu":null,
                        "method":"GET",
                        "position":4,
                        "url":"954324423192494080"
                    },
                    {
                        "allCaption":"",
                        "caption":"综合后勤组",
                        "code":"5",
                        "description":"",
                        "enable":true,
                        "id":5,
                        "menu":null,
                        "method":"GET",
                        "position":5,
                        "url":"954324457296379904"
                    },
                    {
                        "allCaption":"",
                        "caption":"大厅管理组",
                        "code":"6",
                        "description":"",
                        "enable":true,
                        "id":6,
                        "menu":null,
                        "method":"GET",
                        "position":6,
                        "url":"954324486299992064"
                    },
                    {
                        "allCaption":"",
                        "caption":"综合窗口组",
                        "code":"7",
                        "description":"",
                        "enable":true,
                        "id":7,
                        "menu":null,
                        "method":"GET",
                        "position":7,
                        "url":"953359269563961344"
                    }
                ],
                "subMenuItems":[],
                "url":""
            }]
            const filterId = [] // 过滤个人中心
            menuData = menuData.filter(v => !filterId.includes(v.id))
            return menuData
        }
    }
}
</script>

<style lang="scss" scoped>
.layout-menu-content {
    overflow-y: auto;
    height: 100%;
    border-right: none;
    background-color: $--color-bg-menu;

    :deep() {
        .el-menu {
            background-color: $--color-bg-menu;
        }

        .el-submenu__title {
            color: $--color-text-menu;

            &:hover {
                background-color: rgba($--color-primary, 10%);
            }

            &:focus {
                background-color: unset;
            }

            i {
                margin-right: 8px;
                color: $--color-text-menu;
            }
        }

        .el-menu-item {
            border-left: 2px solid transparent;
            color: $--color-text-menu;

            &.is-active {
                background-image: linear-gradient(90deg, #1b2443, #1c2646);
                border-image: linear-gradient(0deg, rgba($--color-primary, .9), rgba($--color-primary, .5)) 0 2;
                color: $--color-primary;

                i {
                    color: $--color-primary;
                }
            }

            &:focus {
                background-color: unset;
            }

            &:hover {
                background-color: rgba($--color-primary, 10%);
            }

            /* stylelint-disable-next-line no-descending-specificity */
            i {
                margin-right: 8px;
                color: $--color-text-menu;
            }
        }
    }
}
</style>
